package com.example.mobilnaksiazkazdrowia;

public enum BDKomunikacjaCel {
        POBIERZ_CZY_UZYTKOWNIK_ISTNIEJE,
        POBIERZ_JAKI_UZYTKOWNIK,
        POBIERZ_MIASTA,
        POBIERZ_ULICE,
        POBIERZ_DANE_OSOBOWE,
        POBIERZ_DANE_O_ZWIERZETACH,
        POBIERZ_RASY_PSOW,
        POBIERZ_DANE_O_WIZYTACH,

        WPROWADZ_NOWE_WIZYTY,
        WPROWADZ_ZAPLANOWANA_WIZYTE,
        ZAREJESTRUJ_UZYTKOWNIKA,
        WPROWADZ_PSA

}

